name: Test Docker Runner

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check Docker
        shell: powershell
        run: |
          docker version

      - name: Check Docker Engine
        shell: powershell
        run: |
          docker info

      - name: List containers
        shell: powershell
        run: |
          docker ps